# -*- coding: utf-8 -*-
"""covid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNd8eXPLpJdb6mp3ffK4Ddt5VwwR9mjQ
"""

!pip install faker
import pandas as pd
import numpy as np
from faker import Faker
import random
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

fake = Faker()

countries = ['India', 'USA', 'Brazil', 'UK', 'Germany', 'France', 'Italy', 'Spain']

data = []

for _ in range(1000):
    date = fake.date_between(start_date='-2y', end_date='today')
    country = random.choice(countries)

    confirmed = random.randint(1000, 100000)
    deaths = random.randint(10, confirmed // 10)
    recovered = random.randint(100, confirmed - deaths)

    active = confirmed - deaths - recovered

    data.append([date, country, confirmed, deaths, recovered, active])

df = pd.DataFrame(data, columns=['Date', 'Country', 'Confirmed', 'Deaths', 'Recovered', 'Active'])

df.head()

df['Date'] = pd.to_datetime(df['Date'])
df.fillna(0, inplace=True)
df.drop_duplicates(inplace=True)

print("Total Confirmed:", df['Confirmed'].sum())
print("Total Deaths:", df['Deaths'].sum())
print("Total Recovered:", df['Recovered'].sum())

trend = df.groupby('Date')[['Confirmed', 'Deaths', 'Recovered']].sum().reset_index()

plt.figure(figsize=(10,5))
plt.plot(trend['Date'], trend['Confirmed'], label='Confirmed')
plt.plot(trend['Date'], trend['Deaths'], label='Deaths')
plt.plot(trend['Date'], trend['Recovered'], label='Recovered')
plt.legend()
plt.title("COVID-19 Trend Over Time")
plt.show()

country_data = df.groupby('Country')[['Confirmed']].sum().sort_values(by='Confirmed', ascending=False)

country_data.plot(kind='bar', figsize=(10,5), title="Country-wise Cases")
plt.show()

top5 = country_data.head(5).reset_index()

px.pie(top5, values='Confirmed', names='Country', title='Top 5 Countries').show()

px.scatter(df, x='Confirmed', y='Deaths', color='Country',
           title='Confirmed vs Deaths').show()

plt.figure(figsize=(6,4))
sns.heatmap(df[['Confirmed','Deaths','Recovered','Active']].corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()