# -*- coding: utf-8 -*-
"""sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODt_FCiIGlOAEndU4EC0hjwDbYS3lHh9
"""

import pandas as pd
import numpy as np
import random
!pip install faker
from faker import Faker
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

fake = Faker()

stores = ['Store_A', 'Store_B', 'Store_C', 'Store_D']
items = ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Camera']
regions = ['North', 'South', 'East', 'West']

data = []

for i in range(1000):
    date = fake.date_between(start_date='-2y', end_date='today')
    store = random.choice(stores)
    item = random.choice(items)
    region = random.choice(regions)

    sales = random.randint(10, 500)

    data.append([date, store, item, region, sales])

df = pd.DataFrame(data, columns=[
    'Date', 'Store', 'Item', 'Region', 'Sales'
])

df.head()

df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values(by='Date')

print(df.isnull().sum())

df = df.drop_duplicates()

df.info()

print("Total Sales:", df['Sales'].sum())
print("Average Sales:", df['Sales'].mean())
print("Max Sales:", df['Sales'].max())
print("Min Sales:", df['Sales'].min())

trend = df.groupby('Date')['Sales'].sum()

plt.figure()
trend.plot()
plt.title("Sales Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

df['Month'] = df['Date'].dt.to_period('M')
monthly = df.groupby('Month')['Sales'].sum().reset_index()

plt.figure(figsize=(12, 6))
sns.barplot(x='Month', y='Sales', data=monthly, hue='Month', dodge=False, palette='viridis')
plt.title("Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)
plt.legend(title='Month', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

store_sales = df.groupby('Store')['Sales'].sum().reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='Store', y='Sales', data=store_sales, hue='Store', dodge=False, palette='mako')
plt.title("Sales by Store")
plt.xlabel("Store")
plt.ylabel("Total Sales")
plt.legend(title='Store')
plt.show()

item_sales = df.groupby('Item')['Sales'].sum().reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='Item', y='Sales', data=item_sales, hue='Item', dodge=False, palette='crest')
plt.title("Sales by Product")
plt.xlabel("Product")
plt.ylabel("Total Sales")
plt.legend(title='Item')
plt.show()

region_sales = df.groupby('Region')['Sales'].sum()

plt.pie(region_sales, labels=region_sales.index, autopct='%1.1f%%')
plt.title("Sales by Region")
plt.show()

sns.histplot(df['Sales'], bins=30)
plt.title("Sales Distribution")
plt.show()

sns.boxplot(x=df['Sales'])
plt.title("Sales Outliers")
plt.show()

corr = df[['Sales']].corr()

sns.heatmap(corr, annot=True)
plt.title("Correlation Heatmap")
plt.show()

fig = px.line(trend, x=trend.index, y='Sales', title='Sales Trend')
fig.show()

